[package]
name = "cloud-config"
version = "6.3.0"
authors = ["Yieazy <yuitta@163.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "=3.0.0-beta.4"
clap_derive = "=3.0.0-beta.4"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
kms_sm = { package = "kms", path = "../kms" }
toml = "0.5"
hex = "0.4"
regex = "1"
rcgen = "0.8"
x509-parser = "0.12"
