[package]
name = "cloud-config"
version = "6.3.0"
authors = ["Yieazy <yuitta@163.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "=3.0.0-beta.4"
clap_derive = "=3.0.0-beta.4"
log = "0.4"
serde = { version = "1", features = ["derive"] }
kms_sm = { git = "https://github.com/cita-cloud/kms_sm", branch = "v6.3.0", package = "kms" }
toml = "0.5"
hex = "0.4"
regex = "1"
rcgen = { version = "0.8", features = ["pem", "x509-parser"] }
x509-parser = "0.12"
rand = "0.8.4"
libsm = "0.4.0"
anyhow = "1"
fs_extra = "1.2"
